import type { CombatCharacter } from '@/graph/state';

export function basePlayerFighter(partial?: Partial<CombatCharacter>): CombatCharacter {
  return {
    id: 'player-fighter',
    name: 'Sir Amaranth',
    hp: 36,
    maxHp: 36,
    tempHp: 0,
    armorClass: 18,
    position: { x: 2, y: 2 },
    initiative: 0,
    avatar: 'player-fighter',
    isPlayer: true,
    strength: 18,
    dexterity: 12,
    constitution: 16,
    intelligence: 10,
    wisdom: 11,
    charisma: 10,
    proficiencyBonus: 3,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
    ...partial,
  };
}

export function basePlayerWizard(partial?: Partial<CombatCharacter>): CombatCharacter {
  return {
    id: 'player-wizard',
    name: 'Lyra the Bright',
    hp: 22,
    maxHp: 22,
    tempHp: 0,
    armorClass: 14,
    position: { x: 2, y: 4 },
    initiative: 0,
    avatar: 'player-wizard',
    isPlayer: true,
    strength: 8,
    dexterity: 14,
    constitution: 12,
    intelligence: 18,
    wisdom: 14,
    charisma: 12,
    proficiencyBonus: 3,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
    ...partial,
  };
}

export function baseGoblin(id: string, name: string, position: { x: number; y: number }): CombatCharacter {
  return {
    id,
    name,
    hp: 14,
    maxHp: 14,
    tempHp: 0,
    armorClass: 13,
    position,
    initiative: 0,
    avatar: id,
    isPlayer: false,
    strength: 8,
    dexterity: 14,
    constitution: 10,
    intelligence: 10,
    wisdom: 8,
    charisma: 8,
    proficiencyBonus: 2,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
  };
}

export function hobgoblinCaptain(): CombatCharacter {
  return {
    id: 'enemy-hobgoblin',
    name: 'Hobgoblin Captain',
    hp: 45,
    maxHp: 45,
    tempHp: 0,
    armorClass: 17,
    position: { x: 7, y: 6 },
    initiative: 0,
    avatar: 'enemy-hobgoblin',
    isPlayer: false,
    strength: 17,
    dexterity: 13,
    constitution: 14,
    intelligence: 12,
    wisdom: 10,
    charisma: 12,
    proficiencyBonus: 3,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
  };
}

export function goblinArcher(): CombatCharacter {
  return {
    id: 'enemy-archer',
    name: 'Goblin Sharpshooter',
    hp: 18,
    maxHp: 18,
    tempHp: 0,
    armorClass: 14,
    position: { x: 9, y: 3 },
    initiative: 0,
    avatar: 'enemy-archer',
    isPlayer: false,
    strength: 8,
    dexterity: 16,
    constitution: 12,
    intelligence: 10,
    wisdom: 10,
    charisma: 8,
    proficiencyBonus: 2,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
  };
}

export function battleRogue(): CombatCharacter {
  return {
    id: 'player-rogue',
    name: 'Selene Quickstep',
    hp: 28,
    maxHp: 28,
    tempHp: 0,
    armorClass: 15,
    position: { x: 2, y: 8 },
    initiative: 0,
    avatar: 'player-rogue',
    isPlayer: true,
    strength: 10,
    dexterity: 18,
    constitution: 12,
    intelligence: 13,
    wisdom: 12,
    charisma: 14,
    proficiencyBonus: 3,
    speed: 7,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 7,
    conditions: [],
  };
}

export function ranger(): CombatCharacter {
  return {
    id: 'player-ranger',
    name: 'Kael Windstrider',
    hp: 30,
    maxHp: 30,
    tempHp: 0,
    armorClass: 15,
    position: { x: 3, y: 10 },
    initiative: 0,
    avatar: 'player-ranger',
    isPlayer: true,
    strength: 12,
    dexterity: 18,
    constitution: 13,
    intelligence: 12,
    wisdom: 15,
    charisma: 11,
    proficiencyBonus: 3,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
  };
}

export function cleric(partial?: Partial<CombatCharacter>): CombatCharacter {
  return {
    id: 'player-cleric',
    name: 'Brother Alden',
    hp: 32,
    maxHp: 32,
    tempHp: 0,
    armorClass: 18,
    position: { x: 2, y: 9 },
    initiative: 0,
    avatar: 'player-cleric',
    isPlayer: true,
    strength: 14,
    dexterity: 10,
    constitution: 14,
    intelligence: 12,
    wisdom: 18,
    charisma: 13,
    proficiencyBonus: 3,
    speed: 6,
    reach: 1,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 6,
    conditions: [],
    ...partial,
  };
}

export function ogre(): CombatCharacter {
  return {
    id: 'enemy-ogre',
    name: 'Ogre Brute',
    hp: 59,
    maxHp: 59,
    tempHp: 0,
    armorClass: 11,
    position: { x: 9, y: 6 },
    initiative: 0,
    avatar: 'enemy-ogre',
    isPlayer: false,
    strength: 19,
    dexterity: 8,
    constitution: 16,
    intelligence: 5,
    wisdom: 7,
    charisma: 7,
    proficiencyBonus: 2,
    speed: 4,
    reach: 2,
    hasMoved: false,
    hasActed: false,
    hasReaction: true,
    hasBonusAction: true,
    movementRemaining: 4,
    conditions: [],
  };
}
