/**
 * Biome Definitions - Static Data
 * 32 biome types with complete climate and visual properties
 * Exception to <280L rule: Static data (Rule 25)
 */

import type { BiomeType, BiomeDefinition } from './types';

export const BIOMES: Record<BiomeType, BiomeDefinition> = {
  // Oceans
  ocean: {
    type: 'ocean',
    name: 'Ocean',
    description: 'Deep waters covering vast areas',
    temperature: { min: -0.3, max: 0.7 },
    moisture: { min: 0.3, max: 1.0 },
    continentalness: { min: -1.0, max: -0.4 },
    erosion: { min: -1.0, max: 1.0 },
    weirdness: { min: -1.0, max: 1.0 },
    grassColor: '#4c9c3f',
    foliageColor: '#3f9c4c',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: -0.8,
    elevationVariance: 0.1,
    surfaceRoughness: 0.2,
    treeDensity: 0.0,
    rockDensity: 0.01,
    grassDensity: 0.0,
    flowerDensity: 0.0,
    surfaceBlock: 'water',
    subsurfaceBlock: 'gravel',
    undergroundBlock: 'stone',
  },

  deep_ocean: {
    type: 'deep_ocean',
    name: 'Deep Ocean',
    description: 'Extremely deep ocean trenches',
    temperature: { min: -0.5, max: 0.5 },
    moisture: { min: 0.5, max: 1.0 },
    continentalness: { min: -1.0, max: -0.7 },
    erosion: { min: -1.0, max: 1.0 },
    weirdness: { min: -1.0, max: 1.0 },
    grassColor: '#4c9c3f',
    foliageColor: '#3f9c4c',
    waterColor: '#1a3a7f',
    skyColor: '#78a7ff',
    baseElevation: -1.5,
    elevationVariance: 0.2,
    surfaceRoughness: 0.3,
    treeDensity: 0.0,
    rockDensity: 0.02,
    grassDensity: 0.0,
    flowerDensity: 0.0,
    surfaceBlock: 'water',
    subsurfaceBlock: 'gravel',
    undergroundBlock: 'stone',
  },

  frozen_ocean: {
    type: 'frozen_ocean',
    name: 'Frozen Ocean',
    description: 'Icy waters with floating icebergs',
    temperature: { min: -1.0, max: -0.4 },
    moisture: { min: 0.3, max: 1.0 },
    continentalness: { min: -1.0, max: -0.3 },
    erosion: { min: -1.0, max: 1.0 },
    weirdness: { min: -1.0, max: 1.0 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: -0.7,
    elevationVariance: 0.15,
    surfaceRoughness: 0.4,
    treeDensity: 0.0,
    rockDensity: 0.05,
    grassDensity: 0.0,
    flowerDensity: 0.0,
    surfaceBlock: 'ice',
    subsurfaceBlock: 'packed_ice',
    undergroundBlock: 'stone',
  },

  // Coasts
  beach: {
    type: 'beach',
    name: 'Beach',
    description: 'Sandy shores along the coast',
    temperature: { min: 0.0, max: 0.8 },
    moisture: { min: 0.0, max: 0.6 },
    continentalness: { min: -0.3, max: 0.0 },
    erosion: { min: -0.5, max: 0.5 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#91bd59',
    foliageColor: '#77ab2f',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.0,
    elevationVariance: 0.05,
    surfaceRoughness: 0.1,
    treeDensity: 0.02,
    rockDensity: 0.01,
    grassDensity: 0.1,
    flowerDensity: 0.01,
    surfaceBlock: 'sand',
    subsurfaceBlock: 'sandstone',
    undergroundBlock: 'stone',
  },

  // Rivers & Lakes
  river: {
    type: 'river',
    name: 'River',
    description: 'Flowing water cutting through the land',
    temperature: { min: -0.2, max: 0.8 },
    moisture: { min: 0.5, max: 1.0 },
    continentalness: { min: -0.2, max: 0.8 },
    erosion: { min: 0.4, max: 1.0 }, // High erosion creates rivers
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#4c9c3f',
    foliageColor: '#3f9c4c',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: -0.2,
    elevationVariance: 0.05,
    surfaceRoughness: 0.1,
    treeDensity: 0.2,
    rockDensity: 0.02,
    grassDensity: 0.6,
    flowerDensity: 0.1,
    surfaceBlock: 'water',
    subsurfaceBlock: 'gravel',
    undergroundBlock: 'stone',
  },

  lake: {
    type: 'lake',
    name: 'Lake',
    description: 'Calm freshwater bodies',
    temperature: { min: -0.2, max: 0.8 },
    moisture: { min: 0.6, max: 1.0 },
    continentalness: { min: 0.0, max: 0.6 },
    erosion: { min: -0.5, max: 0.2 },
    weirdness: { min: -0.8, max: -0.3 },
    grassColor: '#4c9c3f',
    foliageColor: '#3f9c4c',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: -0.1,
    elevationVariance: 0.03,
    surfaceRoughness: 0.05,
    treeDensity: 0.1,
    rockDensity: 0.01,
    grassDensity: 0.5,
    flowerDensity: 0.15,
    surfaceBlock: 'water',
    subsurfaceBlock: 'clay',
    undergroundBlock: 'stone',
  },

  frozen_river: {
    type: 'frozen_river',
    name: 'Frozen River',
    description: 'Icy rivers in cold regions',
    temperature: { min: -1.0, max: -0.2 },
    moisture: { min: 0.4, max: 1.0 },
    continentalness: { min: -0.2, max: 0.8 },
    erosion: { min: 0.3, max: 1.0 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: -0.1,
    elevationVariance: 0.05,
    surfaceRoughness: 0.15,
    treeDensity: 0.05,
    rockDensity: 0.03,
    grassDensity: 0.2,
    flowerDensity: 0.0,
    surfaceBlock: 'ice',
    subsurfaceBlock: 'gravel',
    undergroundBlock: 'stone',
  },

  // Wetlands
  swamp: {
    type: 'swamp',
    name: 'Swamp',
    description: 'Murky wetlands with standing water',
    temperature: { min: 0.4, max: 0.9 },
    moisture: { min: 0.7, max: 1.0 },
    continentalness: { min: -0.1, max: 0.4 },
    erosion: { min: -0.3, max: 0.3 },
    weirdness: { min: -0.3, max: 0.7 },
    grassColor: '#6a7039',
    foliageColor: '#6a7039',
    waterColor: '#617b64',
    skyColor: '#78a7ff',
    baseElevation: -0.05,
    elevationVariance: 0.08,
    surfaceRoughness: 0.3,
    treeDensity: 0.3,
    rockDensity: 0.01,
    grassDensity: 0.8,
    flowerDensity: 0.05,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  mangrove_swamp: {
    type: 'mangrove_swamp',
    name: 'Mangrove Swamp',
    description: 'Tropical swamp with mangrove trees',
    temperature: { min: 0.6, max: 1.0 },
    moisture: { min: 0.8, max: 1.0 },
    continentalness: { min: -0.2, max: 0.3 },
    erosion: { min: -0.3, max: 0.3 },
    weirdness: { min: -0.2, max: 0.8 },
    grassColor: '#5c7f42',
    foliageColor: '#5c7f42',
    waterColor: '#3a7a6a',
    skyColor: '#77c7ff',
    baseElevation: 0.0,
    elevationVariance: 0.1,
    surfaceRoughness: 0.4,
    treeDensity: 0.6,
    rockDensity: 0.01,
    grassDensity: 0.7,
    flowerDensity: 0.1,
    surfaceBlock: 'mud',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  // Forests
  jungle: {
    type: 'jungle',
    name: 'Jungle',
    description: 'Dense tropical forest with thick canopy',
    temperature: { min: 0.7, max: 1.0 },
    moisture: { min: 0.7, max: 1.0 },
    continentalness: { min: 0.1, max: 0.7 },
    erosion: { min: -0.4, max: 0.4 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#59c93c',
    foliageColor: '#30b522',
    waterColor: '#3f76e4',
    skyColor: '#77c7ff',
    baseElevation: 0.15,
    elevationVariance: 0.25,
    surfaceRoughness: 0.6,
    treeDensity: 0.9,
    rockDensity: 0.02,
    grassDensity: 0.9,
    flowerDensity: 0.2,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  bamboo_jungle: {
    type: 'bamboo_jungle',
    name: 'Bamboo Jungle',
    description: 'Jungle dominated by bamboo',
    temperature: { min: 0.7, max: 1.0 },
    moisture: { min: 0.7, max: 1.0 },
    continentalness: { min: 0.2, max: 0.7 },
    erosion: { min: -0.3, max: 0.3 },
    weirdness: { min: 0.5, max: 1.0 },
    grassColor: '#59c93c',
    foliageColor: '#30b522',
    waterColor: '#3f76e4',
    skyColor: '#77c7ff',
    baseElevation: 0.1,
    elevationVariance: 0.2,
    surfaceRoughness: 0.5,
    treeDensity: 0.95,
    rockDensity: 0.01,
    grassDensity: 0.8,
    flowerDensity: 0.15,
    surfaceBlock: 'podzol',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  rainforest: {
    type: 'rainforest',
    name: 'Rainforest',
    description: 'Wet tropical forest with constant rainfall',
    temperature: { min: 0.6, max: 0.9 },
    moisture: { min: 0.8, max: 1.0 },
    continentalness: { min: 0.1, max: 0.6 },
    erosion: { min: -0.5, max: 0.2 },
    weirdness: { min: -0.6, max: 0.4 },
    grassColor: '#4c9c3f',
    foliageColor: '#2d8e28',
    waterColor: '#3f76e4',
    skyColor: '#77c7ff',
    baseElevation: 0.1,
    elevationVariance: 0.3,
    surfaceRoughness: 0.7,
    treeDensity: 0.85,
    rockDensity: 0.03,
    grassDensity: 0.95,
    flowerDensity: 0.25,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  tropical_forest: {
    type: 'tropical_forest',
    name: 'Tropical Forest',
    description: 'Warm forest with diverse vegetation',
    temperature: { min: 0.5, max: 0.8 },
    moisture: { min: 0.6, max: 0.9 },
    continentalness: { min: 0.1, max: 0.6 },
    erosion: { min: -0.4, max: 0.3 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#79c05a',
    foliageColor: '#59ae30',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.1,
    elevationVariance: 0.2,
    surfaceRoughness: 0.5,
    treeDensity: 0.75,
    rockDensity: 0.02,
    grassDensity: 0.8,
    flowerDensity: 0.3,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  forest: {
    type: 'forest',
    name: 'Forest',
    description: 'Temperate forest with oak trees',
    temperature: { min: 0.2, max: 0.6 },
    moisture: { min: 0.4, max: 0.8 },
    continentalness: { min: 0.1, max: 0.7 },
    erosion: { min: -0.4, max: 0.4 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#79c05a',
    foliageColor: '#59ae30',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.1,
    elevationVariance: 0.15,
    surfaceRoughness: 0.4,
    treeDensity: 0.6,
    rockDensity: 0.02,
    grassDensity: 0.7,
    flowerDensity: 0.2,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  birch_forest: {
    type: 'birch_forest',
    name: 'Birch Forest',
    description: 'Forest of tall birch trees',
    temperature: { min: 0.3, max: 0.6 },
    moisture: { min: 0.5, max: 0.8 },
    continentalness: { min: 0.2, max: 0.7 },
    erosion: { min: -0.3, max: 0.3 },
    weirdness: { min: 0.3, max: 0.8 },
    grassColor: '#88bb67',
    foliageColor: '#6ba941',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.1,
    elevationVariance: 0.12,
    surfaceRoughness: 0.3,
    treeDensity: 0.7,
    rockDensity: 0.01,
    grassDensity: 0.6,
    flowerDensity: 0.25,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  dark_forest: {
    type: 'dark_forest',
    name: 'Dark Forest',
    description: 'Dense forest with thick canopy',
    temperature: { min: 0.2, max: 0.6 },
    moisture: { min: 0.6, max: 0.9 },
    continentalness: { min: 0.2, max: 0.7 },
    erosion: { min: -0.4, max: 0.2 },
    weirdness: { min: -0.8, max: -0.3 },
    grassColor: '#507a32',
    foliageColor: '#2d6b22',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.15,
    elevationVariance: 0.2,
    surfaceRoughness: 0.5,
    treeDensity: 0.9,
    rockDensity: 0.03,
    grassDensity: 0.5,
    flowerDensity: 0.05,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  taiga: {
    type: 'taiga',
    name: 'Taiga',
    description: 'Cold forest of spruce trees',
    temperature: { min: -0.2, max: 0.3 },
    moisture: { min: 0.4, max: 0.8 },
    continentalness: { min: 0.2, max: 0.8 },
    erosion: { min: -0.4, max: 0.4 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#86b776',
    foliageColor: '#619961',
    waterColor: '#3f76e4',
    skyColor: '#7da2ff',
    baseElevation: 0.15,
    elevationVariance: 0.18,
    surfaceRoughness: 0.4,
    treeDensity: 0.5,
    rockDensity: 0.03,
    grassDensity: 0.5,
    flowerDensity: 0.05,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  snowy_taiga: {
    type: 'snowy_taiga',
    name: 'Snowy Taiga',
    description: 'Snow-covered taiga',
    temperature: { min: -0.5, max: -0.1 },
    moisture: { min: 0.4, max: 0.8 },
    continentalness: { min: 0.2, max: 0.8 },
    erosion: { min: -0.4, max: 0.4 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: 0.2,
    elevationVariance: 0.2,
    surfaceRoughness: 0.4,
    treeDensity: 0.4,
    rockDensity: 0.04,
    grassDensity: 0.3,
    flowerDensity: 0.0,
    surfaceBlock: 'snow',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  // Plains & Grasslands
  plains: {
    type: 'plains',
    name: 'Plains',
    description: 'Flat grasslands',
    temperature: { min: 0.3, max: 0.7 },
    moisture: { min: 0.2, max: 0.6 },
    continentalness: { min: 0.2, max: 0.8 },
    erosion: { min: -0.3, max: 0.2 },
    weirdness: { min: -0.3, max: 0.3 },
    grassColor: '#91bd59',
    foliageColor: '#77ab2f',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.1,
    elevationVariance: 0.05,
    surfaceRoughness: 0.1,
    treeDensity: 0.05,
    rockDensity: 0.01,
    grassDensity: 0.8,
    flowerDensity: 0.3,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  sunflower_plains: {
    type: 'sunflower_plains',
    name: 'Sunflower Plains',
    description: 'Plains covered in sunflowers',
    temperature: { min: 0.4, max: 0.7 },
    moisture: { min: 0.3, max: 0.6 },
    continentalness: { min: 0.3, max: 0.8 },
    erosion: { min: -0.2, max: 0.2 },
    weirdness: { min: 0.5, max: 1.0 },
    grassColor: '#91bd59',
    foliageColor: '#77ab2f',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.1,
    elevationVariance: 0.05,
    surfaceRoughness: 0.1,
    treeDensity: 0.02,
    rockDensity: 0.01,
    grassDensity: 0.7,
    flowerDensity: 0.9,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  meadow: {
    type: 'meadow',
    name: 'Meadow',
    description: 'Flower-filled mountain meadow',
    temperature: { min: 0.2, max: 0.5 },
    moisture: { min: 0.5, max: 0.8 },
    continentalness: { min: 0.4, max: 0.9 },
    erosion: { min: -0.6, max: -0.2 },
    weirdness: { min: -0.4, max: 0.4 },
    grassColor: '#83bb6d',
    foliageColor: '#63a948',
    waterColor: '#0e4ecf',
    skyColor: '#7fa1ff',
    baseElevation: 0.5,
    elevationVariance: 0.15,
    surfaceRoughness: 0.3,
    treeDensity: 0.1,
    rockDensity: 0.05,
    grassDensity: 0.9,
    flowerDensity: 0.6,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  savanna: {
    type: 'savanna',
    name: 'Savanna',
    description: 'Warm grassland with scattered trees',
    temperature: { min: 0.6, max: 1.0 },
    moisture: { min: 0.0, max: 0.4 },
    continentalness: { min: 0.3, max: 0.8 },
    erosion: { min: -0.3, max: 0.3 },
    weirdness: { min: -0.3, max: 0.3 },
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.12,
    elevationVariance: 0.1,
    surfaceRoughness: 0.2,
    treeDensity: 0.15,
    rockDensity: 0.02,
    grassDensity: 0.6,
    flowerDensity: 0.05,
    surfaceBlock: 'grass',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  // Dry/Hot
  badlands: {
    type: 'badlands',
    name: 'Badlands',
    description: 'Eroded red rock formations',
    temperature: { min: 0.7, max: 1.0 },
    moisture: { min: -1.0, max: 0.1 },
    continentalness: { min: 0.4, max: 0.9 },
    erosion: { min: 0.3, max: 1.0 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#90814d',
    foliageColor: '#9e814d',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.3,
    elevationVariance: 0.4,
    surfaceRoughness: 0.8,
    treeDensity: 0.0,
    rockDensity: 0.1,
    grassDensity: 0.1,
    flowerDensity: 0.0,
    surfaceBlock: 'red_sand',
    subsurfaceBlock: 'terracotta',
    undergroundBlock: 'stone',
  },

  desert: {
    type: 'desert',
    name: 'Desert',
    description: 'Hot sandy wasteland',
    temperature: { min: 0.8, max: 1.0 },
    moisture: { min: -1.0, max: 0.2 },
    continentalness: { min: 0.2, max: 0.9 },
    erosion: { min: -0.3, max: 0.5 },
    weirdness: { min: -0.4, max: 0.4 },
    grassColor: '#bfb755',
    foliageColor: '#aea42a',
    waterColor: '#3f76e4',
    skyColor: '#78a7ff',
    baseElevation: 0.1,
    elevationVariance: 0.1,
    surfaceRoughness: 0.3,
    treeDensity: 0.001,
    rockDensity: 0.02,
    grassDensity: 0.05,
    flowerDensity: 0.0,
    surfaceBlock: 'sand',
    subsurfaceBlock: 'sandstone',
    undergroundBlock: 'stone',
  },

  // Cold
  snowy_plains: {
    type: 'snowy_plains',
    name: 'Snowy Plains',
    description: 'Flat snow-covered land',
    temperature: { min: -0.8, max: -0.2 },
    moisture: { min: 0.2, max: 0.7 },
    continentalness: { min: 0.2, max: 0.8 },
    erosion: { min: -0.3, max: 0.3 },
    weirdness: { min: -0.3, max: 0.3 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: 0.15,
    elevationVariance: 0.05,
    surfaceRoughness: 0.2,
    treeDensity: 0.0,
    rockDensity: 0.02,
    grassDensity: 0.2,
    flowerDensity: 0.0,
    surfaceBlock: 'snow',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  ice_spikes: {
    type: 'ice_spikes',
    name: 'Ice Spikes',
    description: 'Frozen wasteland with ice spikes',
    temperature: { min: -1.0, max: -0.3 },
    moisture: { min: 0.3, max: 0.8 },
    continentalness: { min: 0.3, max: 0.8 },
    erosion: { min: -0.4, max: 0.2 },
    weirdness: { min: 0.6, max: 1.0 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: 0.2,
    elevationVariance: 0.15,
    surfaceRoughness: 0.6,
    treeDensity: 0.0,
    rockDensity: 0.2,
    grassDensity: 0.0,
    flowerDensity: 0.0,
    surfaceBlock: 'packed_ice',
    subsurfaceBlock: 'snow',
    undergroundBlock: 'stone',
  },

  tundra: {
    type: 'tundra',
    name: 'Tundra',
    description: 'Cold, barren land',
    temperature: { min: -0.6, max: -0.1 },
    moisture: { min: 0.1, max: 0.5 },
    continentalness: { min: 0.3, max: 0.9 },
    erosion: { min: -0.2, max: 0.4 },
    weirdness: { min: -0.4, max: 0.4 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: 0.1,
    elevationVariance: 0.08,
    surfaceRoughness: 0.2,
    treeDensity: 0.0,
    rockDensity: 0.05,
    grassDensity: 0.1,
    flowerDensity: 0.0,
    surfaceBlock: 'snow',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  // Mountains
  mountains: {
    type: 'mountains',
    name: 'Mountains',
    description: 'Tall rocky peaks',
    temperature: { min: -0.3, max: 0.5 },
    moisture: { min: 0.2, max: 0.7 },
    continentalness: { min: 0.5, max: 1.0 },
    erosion: { min: -1.0, max: -0.3 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#8ab689',
    foliageColor: '#6da36b',
    waterColor: '#0e4ecf',
    skyColor: '#7fa1ff',
    baseElevation: 0.7,
    elevationVariance: 0.5,
    surfaceRoughness: 0.9,
    treeDensity: 0.1,
    rockDensity: 0.3,
    grassDensity: 0.3,
    flowerDensity: 0.05,
    surfaceBlock: 'stone',
    subsurfaceBlock: 'stone',
    undergroundBlock: 'stone',
  },

  snowy_mountains: {
    type: 'snowy_mountains',
    name: 'Snowy Mountains',
    description: 'Snow-capped peaks',
    temperature: { min: -1.0, max: 0.0 },
    moisture: { min: 0.3, max: 0.8 },
    continentalness: { min: 0.5, max: 1.0 },
    erosion: { min: -1.0, max: -0.3 },
    weirdness: { min: -0.5, max: 0.5 },
    grassColor: '#80b497',
    foliageColor: '#60a17b',
    waterColor: '#3d57d6',
    skyColor: '#7fa1ff',
    baseElevation: 0.8,
    elevationVariance: 0.6,
    surfaceRoughness: 0.95,
    treeDensity: 0.02,
    rockDensity: 0.4,
    grassDensity: 0.1,
    flowerDensity: 0.0,
    surfaceBlock: 'snow',
    subsurfaceBlock: 'stone',
    undergroundBlock: 'stone',
  },

  // Special
  volcanic: {
    type: 'volcanic',
    name: 'Volcanic',
    description: 'Active volcanic region',
    temperature: { min: 0.8, max: 1.0 },
    moisture: { min: -0.5, max: 0.3 },
    continentalness: { min: 0.4, max: 0.9 },
    erosion: { min: -0.8, max: -0.2 },
    weirdness: { min: 0.7, max: 1.0 },
    grassColor: '#4c4c4c',
    foliageColor: '#3c3c3c',
    waterColor: '#ff4400',
    skyColor: '#6b6b84',
    baseElevation: 0.4,
    elevationVariance: 0.6,
    surfaceRoughness: 0.95,
    treeDensity: 0.0,
    rockDensity: 0.5,
    grassDensity: 0.0,
    flowerDensity: 0.0,
    surfaceBlock: 'basalt',
    subsurfaceBlock: 'blackstone',
    undergroundBlock: 'stone',
  },

  mushroom_island: {
    type: 'mushroom_island',
    name: 'Mushroom Island',
    description: 'Rare island covered in giant mushrooms',
    temperature: { min: 0.4, max: 0.7 },
    moisture: { min: 0.6, max: 1.0 },
    continentalness: { min: -0.3, max: 0.2 },
    erosion: { min: -0.4, max: 0.1 },
    weirdness: { min: -1.0, max: -0.7 },
    grassColor: '#55c93f',
    foliageColor: '#2bbb0f',
    waterColor: '#8a8997',
    skyColor: '#78a7ff',
    baseElevation: 0.2,
    elevationVariance: 0.15,
    surfaceRoughness: 0.3,
    treeDensity: 0.5,
    rockDensity: 0.01,
    grassDensity: 0.3,
    flowerDensity: 0.6,
    surfaceBlock: 'mycelium',
    subsurfaceBlock: 'dirt',
    undergroundBlock: 'stone',
  },

  void: {
    type: 'void',
    name: 'Void',
    description: 'Empty space above ground level (sky)',
    temperature: { min: -1.0, max: 1.0 },
    moisture: { min: -1.0, max: 1.0 },
    continentalness: { min: -1.0, max: 1.0 },
    erosion: { min: -1.0, max: 1.0 },
    weirdness: { min: -1.0, max: 1.0 },
    grassColor: '#ffffff',
    foliageColor: '#ffffff',
    waterColor: '#ffffff',
    skyColor: '#78a7ff',
    baseElevation: 0.0,
    elevationVariance: 0.0,
    surfaceRoughness: 0.0,
    treeDensity: 0.0,
    rockDensity: 0.0,
    grassDensity: 0.0,
    flowerDensity: 0.0,
    surfaceBlock: 'air',
    subsurfaceBlock: 'air',
    undergroundBlock: 'air',
  },
};

/**
 * Climate data for a point in the world
 */
