import dotenv from 'dotenv';
dotenv.config();

import { getStrapiClient } from './utils/strapi-client';
import { generateImageGemini } from '../src/utils/llm/image';

// Constants
const MODEL = process.env.GEMINI_IMAGE_MODEL || 'gemini-2.5-flash-image';

console.log(`
MODEL: ${MODEL}
`);

const client = getStrapiClient();

async function main() {
  console.log(`Starting Monster Image Generation (Client Mode)`);
  console.log(`Model: ${MODEL}`);

  try {
    // Parse CLI args for limit
    const args = process.argv.slice(2);
    const limitArg = args.find((arg) => arg.startsWith('--limit='));
    const limit = limitArg ? parseInt(limitArg.split('=')[1], 10) : 5;

    // Fetch Monsters without images
    // Note: 'monsters' is the usual plural collection name.
    // Filters syntax for client: filters[image][$null]=true
    const response: any = await client.collection('monsters').find({
      filters: {
        image: {
          $null: true,
        } as any,
      },
      pagination: {
        pageSize: limit,
      },
      populate: '*', // Need fields for prompt
    });

    const monsters = response.data;
    console.log(`Found ${monsters.length} monsters without images (Limit: ${limit}).`);

    let successCount = 0;
    let failureCount = 0;

    for (const monster of monsters) {
      console.log(`\n🎨 Generating image for: ${monster.name} [${monster.slug}]`);

      try {
        // 1. Construct Prompt
        // Handle flattened or nested response structure
        const attr = monster.attributes || monster;

        const size = attr.size || 'Medium';
        const type = attr.type || 'Creature';
        const align = attr.alignment || 'Unaligned';
        let descText = '';

        if (Array.isArray(attr.description)) {
          descText = attr.description
            .map((block: any) => block.children?.map((c: any) => c.text).join('') || '')
            .join(' ');
        } else if (typeof attr.description === 'string') {
          descText = attr.description;
        }

        const truncatedDesc = descText.slice(0, 300);
        const prompt = `Squared 1x1 image of ${attr.name}, ${size} ${type} ${align}. ${truncatedDesc}. Style: Magic the Gathering illustration, oil painting, high fantasy, detailed, dramatic lighting, white background.`;

        console.log(`   Prompt: "${prompt.slice(0, 50)}..."`);

        // 2. Generate Image (Internal Utility calling Google API)
        const result = await generateImageGemini(
          {
            prompt: prompt,
            aspectRatio: '1:1',
          },
          MODEL
        );

        if (result && result.url) {
          console.log(`   ✅ Image generated.`);

          // 3. Convert Data URI to Buffer for Upload
          // URL format: data:image/png;base64,....
          const matches = result.url.match(/^data:([A-Za-z-+/]+);base64,(.+)$/);
          if (!matches || matches.length !== 3) {
            throw new Error('Invalid base64 string returned from Gemini');
          }

          const mimeType = matches[1];
          const buffer = Buffer.from(matches[2], 'base64');
          const ext = `.${mimeType.split('/')[1].replace('jpeg', 'jpg')}`;
          const filename = `monster-${attr.slug}${ext}`;

          // 4. Upload using Client
          console.log(`   Uploading ${filename}...`);
          const uploadRes = await client.files.upload(buffer, {
            filename: filename,
            mimetype: mimeType,
            fileInfo: {
              name: filename,
              alternativeText: attr.name,
              caption: 'Generated by Gemini',
            },
          });

          // Result is array
          const uploadedFile = Array.isArray(uploadRes) ? uploadRes[0] : uploadRes;

          if (uploadedFile && uploadedFile.id) {
            console.log(`   ✅ Uploaded ID: ${uploadedFile.id}`);

            // 5. Associating with Monster
            // 'monsters' collection update
            // ID might be documentId (Strapi 5) or id (Strapi 4). Client usually handles ID in URL.
            // If using document service (internal) we used documentId.
            // Client .update(id, data)
            // Try using documentId if available, else id.
            const updateId = monster.documentId || monster.id;

            await client.collection('monsters').update(updateId, {
              image: uploadedFile.id,
            });

            console.log(`   ✅ Associated with Monster.`);
            successCount++;
          } else {
            console.error('   ❌ Upload failed, no ID returned.');
            failureCount++;
          }
        }
      } catch (err: any) {
        console.error(`   ❌ Failed: ${err.message}`);
        failureCount++;
      }
    }

    console.log(`\n🎉 Finished! Success: ${successCount}, Failures: ${failureCount}`);
  } catch (error: any) {
    if (error.status === 403) {
      console.error('❌ Authorization failed (403). Check your API Token.');
    } else {
      console.error('Script failed:', error);
    }
  }
}

main();
