import { Attribute, CharacterSheet } from './types/shared';

export const ATTRIBUTES: Attribute[] = [
  Attribute.STR,
  Attribute.DEX,
  Attribute.CON,
  Attribute.INT,
  Attribute.WIS,
  Attribute.CHA,
];

export const SKILLS_LIST = [
  'Acrobatics',
  'Appraise',
  'Bluff',
  'Climb',
  'Craft',
  'Diplomacy',
  'Disable Device',
  'Disguise',
  'Escape Artist',
  'Fly',
  'Handle Animal',
  'Heal',
  'Intimidate',
  'Knowledge (Arcana)',
  'Knowledge (Dungeoneering)',
  'Knowledge (Engineering)',
  'Knowledge (Geography)',
  'Knowledge (History)',
  'Knowledge (Local)',
  'Knowledge (Nature)',
  'Knowledge (Nobility)',
  'Knowledge (Planes)',
  'Knowledge (Religion)',
  'Linguistics',
  'Perception',
  'Perform',
  'Profession',
  'Ride',
  'Sense Motive',
  'Sleight of Hand',
  'Spellcraft',
  'Stealth',
  'Survival',
  'Swim',
  'Use Magic Device',
];

export const NEW_CHARACTER_TEMPLATE: Omit<CharacterSheet, 'name' | 'race' | 'characterClass'> = {
  level: 1,
  xp: 0,
  alignment: 'True Neutral',
  background: 'Adventurer',
  hp: 10,
  maxHp: 10,
  temporaryHp: 0,
  hitDice: { total: 1, current: 1 },
  deathSaves: { successes: 0, failures: 0 },
  armorClass: 10,
  initiative: 0,
  speed: 30,
  proficiencyBonus: 2,
  inspiration: false,
  baseAttackBonus: 0,
  attributes: {
    [Attribute.STR]: 10,
    [Attribute.DEX]: 10,
    [Attribute.CON]: 10,
    [Attribute.INT]: 10,
    [Attribute.WIS]: 10,
    [Attribute.CHA]: 10,
  },
  savingThrows: {
    fortitude: 0,
    reflex: 0,
    will: 0,
  },
  skills: SKILLS_LIST.reduce<Record<string, number>>((acc, skill) => {
    acc[skill] = 0;
    return acc;
  }, {}),
  skillDetails: [],
  expertises: [],
  attacks: [],
  equipment: {
    totalWeight: 0,
    inventory: [],
    equippedItems: {
      mainHand: null,
      offHand: null,
      armor: null,
      shield: null,
      head: null,
      cloak: null,
      belt: null,
      boots: null,
      gloves: null,
      ring1: null,
      ring2: null,
      necklace: null,
      accessory1: null,
      accessory2: null,
    },
  },
  currency: { cp: 0, sp: 0, ep: 0, gp: 10, pp: 0 },
  proficienciesAndLanguages: 'Common',
  features: '',
  talents: [],
  appearance: {
    age: 'Unknown',
    height: '5\'8"',
    weight: '160 lbs',
    eyes: 'Brown',
    skin: 'Fair',
    hair: 'Brown',
    description: '',
  },
  personality: {
    traits: '',
    ideals: '',
    bonds: '',
    flaws: '',
  },
  backstory: '',
  backgroundDetails: {
    origin: '',
    upbringing: '',
    motivation: '',
    keyEvents: [],
    allies: [],
  },
  alliesAndOrganizations: '',
  treasure: '',
  resourcePools: [],
  advancementPoints: {
    ability: 0,
    skill: 0,
    talent: 0,
  },
  spellcasting: {
    class: '',
    ability: '',
    saveDC: 10,
    attackBonus: 0,
    cantrips: [],
    spellsKnown: [],
    slots: [],
  },
};
